# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uR20IPy0sJPfqpn0PApCPEgqZ-xQwMO0
"""

import pandas as pd

# Load dataset
df = pd.read_csv("customer_shopping_behavior.csv")

# Preview data
df.head()

# Dataset structure
df.info()

# Summary statistics
df.describe(include="all")

# Check missing values
df.isnull().sum()

# Impute missing review_rating with median per category
df["Review Rating"] = (
    df.groupby("Category")["Review Rating"]
      .transform(lambda x: x.fillna(x.median()))
)

# Verify missing values resolved
df.isnull().sum()

# Convert column names to snake_case
df.columns = df.columns.str.lower().str.replace(" ", "_")

# Rename purchase amount column
df = df.rename(columns={"purchase_amount_(usd)": "purchase_amount"})

df.columns

labels = ["Young Adult", "Adult", "Middle-aged", "Senior"]
df["age_group"] = pd.qcut(df["age"], q=4, labels=labels)

df[["age", "age_group"]].head(10)

frequency_mapping = {
    "Weekly": 7,
    "Bi-Weekly": 14,
    "Fortnightly": 14,
    "Monthly": 30,
    "Quarterly": 90,
    "Every 3 Months": 90,
    "Annually": 365
}

df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

df[["frequency_of_purchases", "purchase_frequency_days"]].head(10)

df[["discount_applied", "promo_code_used"]].head(10)

# Check if both columns are identical
(df["discount_applied"] == df["promo_code_used"]).all()

# Drop redundant column
df = df.drop(columns=["promo_code_used"])

df.columns

!pip install psycopg2-binary sqlalchemy

from sqlalchemy import create_engine

!pip install pymysql sqlalchemy

import pandas as pd
from sqlalchemy import create_engine

!pip install pymysql sqlalchemy

from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "mysql+pymysql://root:ishu2004@ballast.proxy.rlwy.net:57063/railway"
)

!pip install psycopg2-binary sqlalchemy

import pandas as pd
from sqlalchemy import create_engine

from urllib.parse import quote_plus

raw_password = "YOUR_REAL_PASSWORD"
encoded_password = quote_plus(raw_password)
encoded_password

!pip install psycopg2-binary sqlalchemy

from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("dfZBWJxhAMqdppkHPJkYZOCvDrewTxHn")  # VERY IMPORTANT
host = "trolley.proxy.rlwy.net"
port = "21517"
database = "railway"   # Railway default DB name

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

with engine.connect() as conn:
    print(" PostgreSQL connected successfully!")

df.to_sql("customer", engine, if_exists="replace", index=False)
print(" Data loaded into Railway PostgreSQL")

import pandas as pd

pd.read_sql("SELECT COUNT(*) FROM customer;", engine)

pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

pd.read_sql("""
SELECT season,
       COUNT(*) AS orders,
       ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY season
ORDER BY orders DESC;
""", engine)

"""Q1️ Total revenue by Male vs Female"""

pd.read_sql("""
SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;
""", engine)

"""Q2. Customers who used a discount and spent more than average"""

pd.read_sql("""
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >
      (SELECT AVG(purchase_amount) FROM customer);
""", engine)

"""Q3. Top 5 products with highest average review rating"""

pd.read_sql("""
SELECT item_purchased,
       ROUND(AVG(review_rating)::numeric, 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
""", engine)

"""Q4️⃣ Avg purchase: Standard vs Express"""

pd.read_sql("""
SELECT shipping_type,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
""", engine)

"""Q5️⃣ Subscription vs Non-subscription
🔹 Avg spend
"""

pd.read_sql("""
SELECT subscription_status,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend
FROM customer
GROUP BY subscription_status;
""", engine)

"""Total revenue"""

pd.read_sql("""
SELECT subscription_status,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;
""", engine)

"""Q6️⃣ Products with highest % discounted purchases"""

pd.read_sql("""
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*),
           2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
""", engine)

"""Q7️⃣ Customer segmentation (New / Returning / Loyal)"""

pd.read_sql("""
SELECT
    CASE
        WHEN previous_purchases <= 5 THEN 'New'
        WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;
""", engine)

"""Q8️⃣ Top 3 products per category (window function)"""

pd.read_sql("""
SELECT category,
       item_purchased,
       purchase_count
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rnk <= 3;
""", engine)

"""Q9️⃣ Repeat buyers vs subscription"""

pd.read_sql("""
SELECT subscription_status,
       COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
""", engine)

"""Q🔟 Revenue by age group"""

pd.read_sql("""
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
""", engine)

import pandas as pd

query = """
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

df_result = pd.read_sql(query, engine)

df_result

df.to_csv("customer_dashboard_data.csv", index=False)

from google.colab import files
files.download("customer_dashboard_data.csv")

